version: '3.5'

services:
  golang-restful-api-mariadb:
    container_name: "golang-restful-api-mariadb"
    image: mariadb:10.8.3
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_USER: golang
      MARIADB_PASSWORD: golang
